### ISSUE TITLE
zoom-in cursor

### ISSUE THREAD

**Issue by arnaudmilet** [etiennebacher/shinyfullscreen#4]
Thank you for this great package!
For my app, I need to remove the zoom-in cursor.

Can i suggest you to add a param like cursor (TRUE or FALSE) in the fullscreen_this function?
Then you can test if the user need to have a cursor or not :

    if(isTRUE(cursor)){
      shiny::tags$style(
        paste0(
          "#", id_element, "{
    			cursor: -webkit-zoom-in;
    			cursor: -moz-zoom-in;
    		}
        ::backdrop {
            background-color:", bg_color, ";
        }"
        )
      )
      
    }

**Comment by arnaudmilet** [comment]
It should be better like this:
if(isTRUE(cursor)){
  shiny::tags$style(
    paste0(
      "#", id_element, "{
			cursor: -webkit-zoom-in;
			cursor: -moz-zoom-in;
		}"
    )
  )
  
}

**Comment by etiennebacher** [comment]
Hello, thanks for the kind words. The argument "cursor" is now implemented in `fullscreen_this()` and `fullscreen_those()` in the development version (`remotes::install_github("etiennebacher/shinyfullscreen")`).

Note that if you want to change or remove the cursor, you can do it quite easily with some CSS. Below is an example using the "waiting" cursor instead:
```r
### Only works in browser

library(shiny)
library(shinyfullscreen)

ui <- fluidPage(
  tags$head(
    tags$style(
      HTML("
           #plot {
             cursor: wait !important;
           }")
    )
  ),
  fullscreen_this(plotOutput("plot"))
  
  # Also works with magrittr's pipe
  # plotOutput("plot") %>%
  #   fullscreen_this()
)

server <- function(input, output, session) {
  
  output$plot <- renderPlot(plot(mtcars))
  
}

shinyApp(ui, server, options = list(launch.browser = TRUE))
```
