### ISSUE TITLE
Package lacks functions to exit full screen mode

### ISSUE THREAD

**Issue by pamdx** [etiennebacher/shinyfullscreen#5]
The title is pretty straightforward. I'd be nice to have a function to exit full screen mode. I'd like to be able to create a button that toggles between full screen and standard screen, using the `fullscreen_all` function, but there is currently no function that does the reverse of `fullscreen_all`.

**Comment by etiennebacher** [comment]
Hi, this should now be possible. Can you install the development version and test with:
```r
library(shiny)
library(shinyfullscreen)

ui <- fluidPage(
  fullscreen_button(id = "toggle_fs", "Enter/Quit fullscreen", target = "plot"),
  plotOutput("plot")
)

server <- function(input, output){
  
  output$plot <- renderPlot(plot(mtcars))
  
}

shinyApp(ui, server)
```
If you put `target = NULL` (or omit `target`) it will show the whole page on full screen

**Comment by etiennebacher** [comment]
I'm closing this but feel free to reopen in this solution doesn't work or doesn't do what you expected

**Comment by pamdx** [comment]
Awesome, that's what I was looking for! Just one more thing: could it be possible to add an `icon` argument to the function, as with other button functions in Shiny?

I'd like to be able to do something like this:

``` r
fullscreen_button("full_screen", label = "", icon = shiny::icon("expand", lib = "font-awesome"), target = NULL)
```

**Comment by pamdx** [comment]
Just so you know, there seems to be a strange interaction going on between the button and the [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) Chrome/Edge extension. 

Here's what my dashboard looks like with Dark Reader disabled for the page:

![image](https://user-images.githubusercontent.com/59026485/233151658-fd342133-03f9-4c36-9af1-6200f2bf9a16.png)

When I click on the fullscreen button, I get a weird mix of clear and dark mode, which I don't get if I'm toggling fullscreen on/off with the F11 key:

![image](https://user-images.githubusercontent.com/59026485/233151839-10990ff6-5139-418c-8ac2-f2a7efb85ee3.png)

(Just wanted to let you know, since it's quite a popular browser extension)

**Comment by etiennebacher** [comment]
I added the `icon` argument, you just need to reinstall the dev version

> Just so you know, there seems to be a strange interaction going on between the button and the [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) Chrome/Edge extension.

Thanks for the report, unfortunately I'm not sure there's something I can do. This package uses `screenfull.js` under the hood so maybe you can check there if someone reported this issue. Otherwise, it will mean that it's connected to `shiny` and I don't really have the time to investigate it

**Comment by etiennebacher** [comment]
I also updated `screenfull.js`, maybe it will fix your issue

**Comment by pamdx** [comment]
Great, thanks for the option to add an icon to the button! 

Unfortunately I keep getting the strange mix of dark and light mode when I go into full screen. Contrary to what I said earlier, it is not related to the Dark Reader extension: I've tried the app on an another computer without the extension installed and I get the same result. I've tried using Edge, Chrome and Firefox: I always get this bug when I go into fullscreen with the `fullscreen_button()` function, and not when I use the F11 key.

**Comment by etiennebacher** [comment]
It would be really useful to provide a small reproducible example for this.

But again I doubt I can do anything. This package inserts very small Javascript scripts in the app so it probably comes from the interaction between `screenfull.js` and `shiny`.

**Comment by pamdx** [comment]
Here is a simple reproducible example based on the Old Faithful Geyser [app](https://shiny.rstudio.com/gallery/faithful.html) on the rstudio website:

```r
library(shiny)
library(shinyfullscreen)

ui <- bootstrapPage(
  
  selectInput(inputId = "n_breaks",
              label = "Number of bins in histogram (approximate):",
              choices = c(10, 20, 35, 50),
              selected = 20),
  
  checkboxInput(inputId = "individual_obs",
                label = strong("Show individual observations"),
                value = FALSE),
  
  checkboxInput(inputId = "density",
                label = strong("Show density estimate"),
                value = FALSE),
  
  plotOutput(outputId = "main_plot", height = "300px"),
  
  # Display this only if the density is shown
  conditionalPanel(condition = "input.density == true",
                   sliderInput(inputId = "bw_adjust",
                               label = "Bandwidth adjustment:",
                               min = 0.2, max = 2, value = 1, step = 0.2)
  ),
  fullscreen_button("full_screen", label = "Toggle fullscreen", icon = shiny::icon("expand", lib = "font-awesome"), target = NULL)
  
)

server <- function(input, output) {
  
  output$main_plot <- renderPlot({
    
    hist(faithful$eruptions,
         probability = TRUE,
         breaks = as.numeric(input$n_breaks),
         xlab = "Duration (minutes)",
         main = "Geyser eruption duration")
    
    if (input$individual_obs) {
      rug(faithful$eruptions)
    }
    
    if (input$density) {
      dens <- density(faithful$eruptions,
                      adjust = input$bw_adjust)
      lines(dens, col = "blue")
    }
    
  })
}

shinyApp(ui = ui, server = server)
```

I still get the bug with the above:

![image](https://user-images.githubusercontent.com/59026485/233330056-2daeb0b0-894c-4feb-9f96-a3c9dccaa44a.png)

**Comment by etiennebacher** [comment]
I can reproduce but no clue

**Comment by pamdx** [comment]
maybe these StackOverflow questions will help: 

- https://stackoverflow.com/questions/16163089/background-element-goes-black-when-entering-fullscreen-with-html5
- https://stackoverflow.com/questions/60619660/why-does-chrome-fullscreen-make-the-background-black
- https://stackoverflow.com/questions/35244224/fullscreen-api-change-default-color

**Comment by pamdx** [comment]
Note that using the following CSS workaround solves the issue:

```r
library(shiny)
library(shinyfullscreen)

ui <- bootstrapPage(
  
  tags$head(
    # Define fullscreen background color using CSS
    tags$style(HTML(":fullscreen, ::backdrop {
    background-color: rgba(255,255,255,0);}"))
  ),
  
  selectInput(inputId = "n_breaks",
              label = "Number of bins in histogram (approximate):",
              choices = c(10, 20, 35, 50),
              selected = 20),
  
  checkboxInput(inputId = "individual_obs",
                label = strong("Show individual observations"),
                value = FALSE),
  
  checkboxInput(inputId = "density",
                label = strong("Show density estimate"),
                value = FALSE),
  
  plotOutput(outputId = "main_plot", height = "300px"),
  
  # Display this only if the density is shown
  conditionalPanel(condition = "input.density == true",
                   sliderInput(inputId = "bw_adjust",
                               label = "Bandwidth adjustment:",
                               min = 0.2, max = 2, value = 1, step = 0.2)
  ),
  fullscreen_button("full_screen", label = "Toggle fullscreen", icon = shiny::icon("expand", lib = "font-awesome"), target = NULL)
  
)

server <- function(input, output) {
  
  output$main_plot <- renderPlot({
    
    hist(faithful$eruptions,
         probability = TRUE,
         breaks = as.numeric(input$n_breaks),
         xlab = "Duration (minutes)",
         main = "Geyser eruption duration")
    
    if (input$individual_obs) {
      rug(faithful$eruptions)
    }
    
    if (input$density) {
      dens <- density(faithful$eruptions,
                      adjust = input$bw_adjust)
      lines(dens, col = "blue")
    }
    
  })
}

shinyApp(ui = ui, server = server)
```

Source: https://stackoverflow.com/questions/16163089/background-element-goes-black-when-entering-fullscreen-with-html5

**Comment by etiennebacher** [comment]
Thanks a lot for digging into this, I included your CSS directly in the function and the black background doesn't appear anymore.

I tried to use the value `transparent` instead of `rgba(255,255,255,0)` so that it uses the background color of the body if it's specified but it doesn't seem to work. It should be fine for white background though

**Comment by pamdx** [comment]
Alright perfect, this is good enough for me!
